apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minimalist.fullname" . }}-secret
  labels:
    {{- include "minimalist.labels" . | nindent 4 }}
type: Opaque
data:
  VITE_SUPABASE_PUBLISHABLE_KEY: {{ .Values.secrets.supabasePublishableKey | b64enc | quote }}
